### ISSUE TITLE
是否支持query条件过滤

### ISSUE THREAD

**Issue by kerven88** [shinexia/elasticdump#6]
能否支持类似elasticdump的 --searchBody 条件过滤？

  --searchBody='
  {
    "query": {
        "range": {
            "activity.S_T_VD_EVENTOCCURDATE.raw": {
                "gte": "2021-11-18",
                "lt":  "2021-11-19"
            }
        }
    }
  }'

**Comment by shinexia** [comment]
v0.4.0 已支持
