### ISSUE TITLE
dump报错the client noticed that the server is not Elasticsearch and we do not support this unknown product

### ISSUE THREAD

**Issue by kerven88** [shinexia/elasticdump#7]
/opt/elasticdump dump data \
    --host http://localhost:9200 \
    --index forseti-r-20211118 \
    --batch 1000 \
    --file /tmp/111.json \
    --v 4

错误日志：
2021-11-22T06:29:48Z GET http://localhost:9200/ [status:200 request:3ms]
2021/11/22 06:29:48 main.go:21: the client noticed that the server is not Elasticsearch and we do not support this unknown product
github.com/shinexia/elasticdump/pkg/elasticdump.(*ESClient).makeResponse
	/go/src/github.com/shinexia/elasticdump/pkg/elasticdump/client.go:40
github.com/shinexia/elasticdump/pkg/elasticdump.(*ESClient).ScrollStart
	/go/src/github.com/shinexia/elasticdump/pkg/elasticdump/client.go:131
github.com/shinexia/elasticdump/pkg/elasticdump.(*ESClient).DumpData
	/go/src/github.com/shinexia/elasticdump/pkg/elasticdump/client.go:145
github.com/shinexia/elasticdump/pkg/elasticdump.(*Dumper).DumpData.func1
	/go/src/github.com/shinexia/elasticdump/pkg/elasticdump/dumper.go:90
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1581

**Comment by shinexia** [comment]
看下 `curl http://localhost:9200` 的输出结果，当前客户端支持的是 7.x

**Comment by ilyaevseev** [comment]
The same problem with OpenSearch in AWS.

Mapping is dumped ok, but data fails:

```bash
$ elasticdump --host http://vpc-**.us-west-1.es.amazonaws.com --index MyIndex1 dump data -v=4
2024-07-12T21:58:25Z GET http://vpc-**.us-west-1.es.amazonaws.com/ [status:200 request:4ms]
2024/07/12 21:58:26 main.go:21: the client noticed that the server is not Elasticsearch and we do not support this unknown product
```

Cluster info by `curl http://vpc-**.us-west-1.es.amazonaws.com`:
```json
{
  "name" : "...",
  "cluster_name" : "...",
  "cluster_uuid" : "...",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.11.0",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2024-04-03T15:05:03.484045621Z",
    "build_snapshot" : false,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```
